apiVersion: apps/v1
kind: Deployment
metadata:
  name: start
spec:
  replicas: 1
  selector:
    matchLabels:
      app: start
  template:
    metadata:
      labels:
        app: start
    spec:
      containers:
      - image: okteto.dev/start:latest
        name: start
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "$ProxySite"
        - name: Vless_UUID
          value: "c1268ab0-a903-4eff-8be0-55f3b7c9383f"
        - name: Vless_Path
          value: "/m56ftgytrASW"
        - name: Vmess_UUID
          value: "c1268ab0-a903-4eff-8be0-55f3b7c9383f"
        - name: Vmess_Path
          value: "/m57ftgytrASW"
        - name: Share_Path
          value: "$Share_Path"
