apiVersion: apps/v1
kind: Deployment
metadata:
  name: okk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okk
  template:
    metadata:
      labels:
        app: okk
    spec:
      containers:
      - image: okteto.dev/okk:latest
        name: okk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "6a217851-af74-4738-bf76-0c4d0fd156ae"
        - name: Vless_Path
          value: "/hgflshgyv46k"
        - name: Vmess_UUID
          value: "6a217851-af74-4738-bf76-0c4d0fd156ae"
        - name: Vmess_Path
          value: "/vgyt67remhf"
        - name: Share_Path
          value: "$Share_Path"
