apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
      - image: okteto.dev/book:latest
        name: book
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "AYJCSGM/mikutap/archive"
        - name: Vless_UUID
          value: "5c301bb8-6c77-41a0-a606-4ba11bbab084"
        - name: Vless_Path
          value: "/vless"
        - name: Vmess_UUID
          value: "5c301bb8-6c77-41a0-a606-4ba11bbab084"
        - name: Vmess_Path
          value: "/vmess"
        - name: Share_Path
          value: "$Share_Path"
