apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - image: okteto.dev/search:latest
        name: search
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "$ProxySite"
        - name: Vless_UUID
          value: "6a217851-af74-4738-bf76-0c4d0fd156ae"
        - name: Vless_Path
          value: "/hgfV78Lds"
        - name: Vmess_UUID
          value: "6a217851-af74-4738-bf76-0c4d0fd156ae"
        - name: Vmess_Path
          value: "/yhu79MhvM"
        - name: Share_Path
          value: "$Share_Path"
