apiVersion: apps/v1
kind: Deployment
metadata:
  name: outlook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outlook
  template:
    metadata:
      labels:
        app: outlook
    spec:
      containers:
      - image: okteto.dev/outlook:latest
        name: outlook
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "$ProxySite"
        - name: Vless_UUID
          value: "afcec8d5-ac8a-4264-981d-89e11d6c6226"
        - name: Vless_Path
          value: "/hgfV78Lds"
        - name: Vmess_UUID
          value: "afcec8d5-ac8a-4264-981d-89e11d6c6226"
        - name: Vmess_Path
          value: "/yhu79MhvM"
        - name: Share_Path
          value: "$Share_Path"
