apiVersion: apps/v1
kind: Deployment
metadata:
  name: pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pool
  template:
    metadata:
      labels:
        app: pool
    spec:
      containers:
      - image: okteto.dev/pool:latest
        name: pool
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "$ProxySite"
        - name: Vless_UUID
          value: "5c301bb8-6c77-41a0-a606-4ba11bbab084"
        - name: Vless_Path
          value: "/m56ftgytrASW"
        - name: Vmess_UUID
          value: "5c301bb8-6c77-41a0-a606-4ba11bbab084"
        - name: Vmess_Path
          value: "/m57ftgytrASW"
        - name: Share_Path
          value: "$Share_Path"
